# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwitchSpeak-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwitchSpeak-iOS
  pod 'GRDB.swift'

  target 'SwitchSpeak-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwitchSpeak-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
